[package]
description = "Flexperiment Nano Board"
keywords = ["no-std", "stm32"]
license = "MIT OR Apache-2.0"
name = "board_flexperiment_nano"
version = "0.1.0"

[dependencies]
mcu_stm32f0xx = { version = "0.1", path = "../../mcu/stm32f0xx" }

[lib]
path="lib.rs"
